# edit rc
alias ebrc='vim ~/.bashrc && . ~/.bashrc'

# enable color support of ls and also add handy aliases
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# Mornings
alias p='prodcertstatus || prodaccess'

# Blaze
alias bb='blaze build'
alias bba='blaze build :all'
alias bbt='blaze test'
alias bbta='blaze test :all'
alias bbr='blaze run'

# Client checking
alias myclients='ls /google/src/cloud/fredyang'
alias hgclients='hg citc --list'

# Languages
alias py3='python3'

# Tools
alias aristotle_cli=/google/data/ro/projects/aristotle/aristotle_cli.par
alias borg_capacity_cli=/google/data/ro/projects/borg-sre/borg_capacity_cli
alias srsly_cli=/google/data/ro/projects/borg-sre/srsly_cli
alias dedicated_labels=/google/data/ro/projects/borg-sre/dedicated_labels.par
alias ipdb_client=/google/data/ro/projects/netops/ipdb_client
alias reachability='/google/bin/releases/cloudnet-modeling/reachability/reachability.par'
alias machine_picker=/google/data/ro/teams/cloud-capacity-automation/machine_picker_v2/live/machine_picker.par
alias siscli.par='/google/data/ro/buildstatic/projects/production/sisyphus/siscli.par'
alias mkredirect='/google/src/head/depot/google3/corp/g3doc_contrib/tools/mkredirect/mkredirect.sh'

# GCP
alias gcp_proj_number='/google/data/ro/teams/oneplatform/namespace_client --project_ids'
alias gcp_proj_name='/google/data/ro/teams/oneplatform/namespace_client --project_numbers'

# Common Commands
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -iv'
alias mkdir='mkdir -p'
alias ps='ps auxf'
alias less='less -R'
alias apt-get='sudo apt-get'
alias multitail='multitail --no-repeat -c'
alias rmd='rm -rfv '

# Editor
alias vi='vim'
alias svi='sudo vi'

# List stuff
alias la='ls -Alh' # show hidden files
alias ls='ls -aFh --color=always' # add colors and file type extensions
alias lx='ls -lXBh' # sort by extension
alias lk='ls -lSrh' # sort by size
alias lc='ls -lcrh' # sort by change time
alias lu='ls -lurh' # sort by access time
alias lr='ls -lRh' # recursive ls
alias lt='ls -ltrh' # sort by date
alias lm='ls -alh |more' # pipe through 'more'
alias lw='ls -xAh' # wide listing format
alias ll='ls -Fls' # long listing format
alias labc='ls -lap' #alphabetical sort
alias lf="ls -l | egrep -v '^d'" # files only
alias ldir="ls -l | egrep '^d'" # directories only

# Search
alias f="find . | grep "
alias fv="find . | grep -v "

# Util
alias diskspace="du -S | sort -n -r |more"
alias topcpu="/bin/ps -eo pcpu,pid,user,args | sort -k 1 -r | head -10"
alias folders='du -h --max-depth=1'
alias folderssort='find . -maxdepth 1 -type d -print0 | xargs -0 du -sk | sort -rn'
alias tree='tree -CAhF --dirsfirst'
alias treed='tree -CAFd'
alias mountedinfo='df -hT'

# xkcd.com/1168
alias mktar='tar -cvf'
alias mkbz2='tar -cvjf'
alias mkgz='tar -cvzf'
alias untar='tar -xvf'
alias unbz2='tar -xvjf'
alias ungz='tar -xvzf'
