" Makes it work in windows
set nocompatible
source $VIMRUNTIME/vimrc_example.vim
source $VIMRUNTIME/mswin.vim
behave mswin

set diffexpr=MyDiff()
function MyDiff()
    let opt = '-a --binary '
    if &diffopt =~ 'icase' | let opt = opt . '-i ' | endif
    if &diffopt =~ 'iwhite' | let opt = opt . '-b ' | endif
    let arg1 = v:fname_in
    if arg1 =~ ' ' | let arg1 = '"' . arg1 . '"' | endif
    let arg2 = v:fname_new
    if arg2 =~ ' ' | let arg2 = '"' . arg2 . '"' | endif
    let arg3 = v:fname_out
    if arg3 =~ ' ' | let arg3 = '"' . arg3 . '"' | endif
    let eq = ''
    if $VIMRUNTIME =~ ' '
    if &sh =~ '\<cmd'
    let cmd = '""' . $VIMRUNTIME . '\diff"'
    let eq = '"'
    else
    let cmd = substitute($VIMRUNTIME, ' ', '" ', '') . '\diff"'
    endif
    else
    let cmd = $VIMRUNTIME . '\diff'
    endif
    silent execute '!' . cmd . ' ' . opt . arg1 . ' ' . arg2 . ' > ' . arg3 . eq
endfunction



" Custom
set directory=.,$TEMP                   " Gets rid of first error
set number                              " Delicious numbers
set autochdir                           " Automatically cd into the directory that the file is in
set showcmd                             " This shows what you are typing as a command.
set shiftwidth=4                        " Statistically twice as much fun as 2
set softtabstop=4
set autoindent smartindent              " Lazy :|
set expandtab                           " Spaces are pretty imbalanced
set smarttab
set backspace=2                         " Just like notepad now
set cul                                 " Current line highlighting
set showmatch                           " Show matching brackets
set ignorecase                          " Searching made easy
set smartcase
set incsearch
set undolevels=1000                     " Mistakes happen, hundreds of them in fact
set mouse=a                             " Mice are pretty good, sometimes
set wildmenu                            " Remembering file paths is really difficult
set wildmode=list:longest,full
set foldmethod=marker                   " Folds modular code
set hlsearch                            " Highlight search matches
set nohidden                            " Flush buffer on close tab
set nobackup                            " don't do backups on different computers
set display=lastline                    " for super long lines
set wrap                                " wrap visually, not the acutal text in buffer
set textwidth=0                         " don't auto wrap lines
set wrapmargin=0
let g:leave_my_textwidth_alone=1        " Make sure BufReads don't change textwidth

map j gj
map k gk

" Long commands
" Remove any trailing whitespace that is in the file
autocmd BufRead,BufWrite * if ! &bin | silent! %s/\s\+$//ge | endif

" Change any lingering tabs to 4 spaces
autocmd BufRead,BufWrite * if ! &bin | silent! %s/\t/    /ge | endif

" Windows is amazing
autocmd BufNewFile,BufRead *.txt set textwidth=0

" Spellcheck in english, off by default
if version >= 700
    set spl=en spell
    set nospell
endif

" Sexy line number in colorscheme
if has("gui_running")
    colorscheme level28
    set guifont=Consolas
    hi CursorLine term=none cterm=none ctermbg=3
else
    colorscheme darkblue
    hi CursorLine term=none cterm=none ctermbg=0
endif
